### ISSUE TITLE
apk_signature hash

### ISSUE THREAD

**Issue by TimScriptov** [aimardcr/APKKiller#1]
If possible, move the hash to the dex , manifest or assets... To avoid compiling C++ code every time

**Comment by aimardcr** [comment]
I have been thinking about it and I will find an idea for this, but because of this i also need to remake the APKSignReader tool to adapt to the newest source.

**Comment by jbro129** [comment]
> I have been thinking about it and I will find an idea for this, but because of this i also need to remake the APKSignReader tool to adapt to the newest source.

You could look into [ApkSignatureKiller](https://github.com/L-JINBIN/ApkSignatureKiller) to see how you could implement this. The only problem is that many apps/games use techniques such as [SignatureVerificationDemo](https://github.com/aizuzi/SignatureVerificationDemo) which ApkSignatureKiller does not work against. ApkSignatureKiller stops the app from being able to detect invalid signatures via java, but fails when the checks are being done natively.

**Comment by aimardcr** [comment]
I've take a look at SignatureVerificationDemo and APKKiller should bypass
it too, i have been working on a new system for storing license.

**Comment by aimardcr** [comment]
Please check latest commit, now APKKiller is using BinaryReader to decode target app signatures in the [APKKiller.java](https://github.com/aimardcr/APKKiller/blob/master/app/src/main/java/com/kuro/APKKiller.java#L10)

The data are formatted into Base64, which consist these following structure:
```
struct SignData {
   int size;
   byte sign[size];
};
struct data {
  int signCount;
  SignData signData[signCount];
};
```

Please let me know if it works fine for you.
