### ISSUE TITLE
大佬，皮皮虾没成功过签名校验

### ISSUE THREAD

**Issue by tpnet** [aimardcr/APKKiller#24]
现在接入了ApkKiller之后首次打开会崩，然后第二次打开就提示非官方包了。皮皮虾也是跟某音一样的六神签名。
![e33c96e1a45442dc1ee0ae5052f00657](https://github.com/aimardcr/APKKiller/assets/17380722/d0b698b3-5891-4ddc-b449-0d72e69a6040)

**Comment by Kaspek2480** [comment]
(use english)
Maybe application use other ways to detect its modified, try to reverse that :D

**Comment by tpnet** [comment]
> (use english) Maybe application use other ways to detect its modified, try to reverse that :D

Because Pipixia also performs signature verification in native, Hope ApkKiller can pass this signature verification.

**Comment by aimardcr** [comment]
> > (use english) Maybe application use other ways to detect its modified, try to reverse that :D
> 
> Because Pipixia also performs signature verification in native, Hope ApkKiller can pass this signature verification.

This can be achieve by hooking on libc api such as open, fopen, openat, etc. However this won't work if the app is using inline syscall to call those api.
