### ISSUE TITLE
dont work for critical Ops

### ISSUE THREAD

**Issue by WhiskyModz** [aimardcr/APKKiller#3]
nice job i tried this tool for many games and it worked in most of them but not in codm and critical Ops

**Comment by aimardcr** [comment]
it should work for both, i will try and let you know. can you tell me whats wrong?

**Comment by WhiskyModz** [comment]
Have you tried, I'm sure I did everything right, but it didn't work.

**Comment by aimardcr** [comment]
it works for CODM, I haven't tested critical ops, i will let you know.

**Comment by WhiskyModz** [comment]
Ok thanks bro

**Comment by WhiskyModz** [comment]
> it works for CODM, I haven't tested critical ops, i will let you know.

I tried for codm
I got the signature of the game and added it to apkkiller.h
Then I compiled the apk and added it to the codm.
I named the original apk as original.apk and added it to the assets file 
Finally, I opened classes3.dex in codm and com.tencent.tmgp.cod.CODMPrivatePermissionActivity I went to  activity And I found the onCreate method and edited it
Finally, I compiled and uploaded the apk, but I got a Google playstore warning at login.
 Where did I go wrong?

**Comment by TimScriptov** [comment]
@WhiskyModz Perhaps there is a check for the installation source. Example Google Vending

**Comment by MrWildanMD** [comment]
@WhiskyModz can u try using this from @jbro129 repo...[Spoof from playstore](https://github.com/jbro129/jbro129s-tools/blob/main/Install%20Apk%20Drag%20(From%20PlayStore).bat) simply put adb and then drag apk to batch file then try to open again..this will spoof app is installed from playstore
